version: '3.4'

volumes:
  mongo_data:

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis:alpine
  
  catalog:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Services\Catalog\Catalog.API\Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services\Basket\Basket.API\Dockerfile

