version: '3.4'

volumes:
  mongo_data:

services:
  catalogdb:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management-alpine

  basketdb:
    image: redis:alpine

  orderdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: orderdb
    ports:
      - "1435:1433"
    environment:
      MSSQL_SA_PASSWORD: "0x7s-gro9-2rdy"
      ACCEPT_EULA: "Y"

  discountdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: discountdb
    ports:
      - "1434:1433"
    environment:
      MSSQL_SA_PASSWORD: "0x7s-gro9-2rdy"
      ACCEPT_EULA: "Y"

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: .
      dockerfile: Services\Catalog\Catalog.API\Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services\Basket\Basket.API\Dockerfile

  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: Services\Discount\Discount.API\Dockerfile
    ports: 
      - 8002:80
    depends_on: 
      - discountdb
  
  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services\Discount\Discount.Grpc\Dockerfile

  ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services\Ordering\Ordering.API\Dockerfile

  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: ApiGateaways\OcelotApiGw\Dockerfile  

  shopping.aggregator:
    image: ${DOCKER_REGISTRY-}shoppingaggregator
    build:
      context: .
      dockerfile: ApiGateaways\Shopping.Aggregator\Dockerfile