version: '3.4'

services:
   catalogdb:
        container_name: catalogdb
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
   basketdb:
        container_name: basketdb
        restart: always    
        ports:
            - "6379:6379"
   
   basket.api:
        container_name: basket.api
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - "CacheSettings:ConnectionString=basketdb:6379"
        depends_on:
          - basketdb
        ports:
          - "8001:80"

   catalog.api:
        container_name: catalog.api
        build:
          context: .
          dockerfile: Services\Catalog\Catalog.API\Dockerfile
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
          - "ElasticConfiguration:Uri=http://elasticsearch:9200"
        depends_on:
          - catalogdb
        ports:
          - "8000:80"  
        volumes:
          - ./Users/amigo/AppData/Roaming/Microsoft/UserSecrets:/Users/ContainerUser/AppData/Roaming/Microsoft/UserSecrets:ro
volumes:
  mongo_data:

